### PR TITLE
build(deps): bump all dependencies

### LINKED ISSUE #5: Multiple issues. Are pull requests still accepted?
The labeler is exactly what I need, but I'm having multiple issues with it.

1. `Unexpected input(s) 'name', valid inputs are ['repo-token', 'workspace', 'prefix']`

It seems that the parameter `name` does not exist at all.

2. `Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: csi-lk/package-labeler@v1.0.1`

The `action.yml` node version should be updated from `node12` to `node16`.

3. The deps should be updated.

When updating the deps, code modification is required. Should switch to package `@octokit/rest` and use:

```ts
import { Octokit } from '@octokit/rest';

const client = new Octokit({
  auth: token
});
```

4. The docs describe how to use `prefix: "pkg: "`. There is a space behind the colon, so the applied tag should be `pkg: core`. However the space gets trimmed from the prefix and the applied tag is `pkg:core` without space..

Are pull requests still accepted? If so, I would really like to contribute to fix the issues. As an alternative I would fork the repo, apply the patches and release a new workflow. I would prefer the first one.

### PR DESCRIPTION
**Pull request by jrson83**
### Description

I made this changes in mid december already and just created a clean PR again.
I remember the action was working well after making the changes.

### What does this PR implement/fix?

Closes #5 

---

**build(deps): bump all dependencies**
- Bumps [@actions/core] from 1.1.3 to 1.10.0.
- Bumps [@actions/github] from 1.1.0 to 5.1.1.
- Bumps [@types/node] from 12.7.9 to 18.13.00.
- Bumps [prettier] from 1.18.2 to 2.8.4.
- Bumps [typescript] from 3.6.3 to 4.9.5.

**fix: update action.yml**
- fix: add missing branding in schema
- fix: bump node version

**build(deps): add @octokit/rest**

**fix: broken code after deps update**

### CODE REVIEW

**Review by csi-lk — APPROVED** [review]
Thanks for picking this up, approved

**Comment by jrson83** [comment]
> Thanks for picking this up, approved

Thank you. I will add [github-action-ts-run-api](https://github.com/cardinalby/github-action-ts-run-api) which I just found to test github actions locally (without docker). If the test is successful I will merge the PR.

**Comment by alanbbdev** [comment]
hey @jrson83 @csi-lk can we merge this?

**Comment by csi-lk** [comment]
Thanks for tagging me @alanschiobairesdev , I didn't get a notification on this, weird

Merging

**Pull request merged**
